DROP TABLE customers;
DROP TABLE films;
DROP TABLE tickets;

CREATE TABLE customers (
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255),
  funds INT4
);

CREATE TABLE films (
  id SERIAL4 PRIMARY KEY,
  title VARCHAR(255),
  price INT4
);

CREATE TABLE tickets (
  id SERIAL4 PRIMARY KEY,
  customer_id INT4 REFERENCES customers(id) ON DELETE CASCADE, --DELETES ALL ASSOCIATED VISITS IF USER IS DELETED
  film_id INT4 REFERENCES fims(id) ON DELETE CASCADE,  --DELETES ALL ASSOCIATED VISITS IF LOCATION IS DELETED
  
);
